---
- name: add the nf_conntrack module
  become: 'yes'
  modprobe:
    name: nf_conntrack
    state: present
  tags:
    - conntrack
    - sysctl

- name: stat nf_conntrack_tcp_be_liberal
  become: 'yes'
  stat:
    path: /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal
  register: conntrackliberal
  tags:
    - conntrack
    - sysctl

- name: enable nf_conntrack_tcp_be_liberal to keep connections alive
  become: 'yes'
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: "1"
    state: present
    sysctl_set: 'yes'
    reload: 'yes'
  when: conntrackliberal.stat.exists
  tags:
    - conntrack
    - sysctl

- name: ufw installation
  become: 'yes'
  apt:
    name: "ufw"
    state: present
    install_recommends: 'no'
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - packages
    - ufw

- name: ufw installation
  become: 'yes'
  dnf:
    name: "ufw"
  when: ansible_os_family == "RedHat"
  tags:
    - dnf
    - packages
    - ufw

- name: set ufw IPT_SYSCTL
  become: 'yes'
  lineinfile:
    regexp: "^IPT_SYSCTL="
    line: "IPT_SYSCTL=/etc/sysctl.conf"
    dest: /etc/default/ufw
    mode: 0640
    state: present
    create: 'no'
    backrefs: 'yes'
  tags:
    - ufw

- name: allow ssh ufw
  become: 'yes'
  ufw:
    rule: allow
    src: "{{ item }}"
    port: "{{ sshd_port|int }}"
    proto: tcp
  with_items:
    - "{{ sshd_admin_net }}"
  tags:
    - ufw
    - ssh

# https://github.com/ansible/ansible/issues/45446
- name: enable ufw and set default deny incoming
  become: 'yes'
  ufw:
    state: enabled
    direction: incoming
    policy: deny
    logging: low
  tags:
    - ufw
