---
- name: Ensure journald is configured securely
  become: yes
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "(?i)[^\\s #]*{{ item.name }}="
    line: "{{ item.name }}={{ item.value }}"
    state: present
  tags:
    - systemd
    - journald
  loop:
    - { name: "Compress", value: "yes"}
    - { name: "ForwardToSyslog", value: "yes"}
    - { name: "Storage", value: "persistent"}
  notify:
    - reload systemd

- name: Ensure logrotate assigns appropriate permissions
  become: yes
  lineinfile:
    path: /etc/logrotate.conf
    regexp: "(?i)[^\\s #]*create"
    line: "create 0640 root utmp"
    state: present
  tags:
    - logrotate

- name: stat rsyslog.conf
  become: 'yes'
  stat:
    path: /etc/rsyslog.conf
  register: rsyslogconf
  tags:
    - rsyslog

- name: Ensure rsyslog default file permissions configured
  become: 'yes'
  lineinfile:
    regexp: '^\$FileCreateMode'
    line: '$FileCreateMode 0640'
    dest: /etc/rsyslog.conf
    state: present
    create: 'no'
  when: rsyslogconf.stat.exists
  tags:
    - rsyslog
...
