---
- name: Copy tmp.mount (Debian only)
  become: yes
  copy:
    dest: /lib/systemd/system
    mode: 0644
    remote_src: yes
    src: /usr/share/systemd/tmp.mount
    validate: /usr/bin/systemd-analyze verify %s
  when: ansible_os_family == "Debian"
  tags:
    - systemd
    - tmp

- name: Ensure nodev, noexec, and nosuid are set in the /tmp partition
  become: yes
  lineinfile:
    line: Options=mode=1777,strictatime,nosuid,nodev,noexec
    mode: 0644
    path: /lib/systemd/system/tmp.mount
    regexp: ^Options=.*
  tags:
    - systemd
    - tmp

- name: Enable tmp.mount
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    masked: no
    name: tmp.mount
    state: started
  tags:
    - systemd
    - tmp
