---
- name: Harden /tmp
  become: yes
  block:
    - name: Copy tmp.mount (Debian only)
      copy:
        dest: /etc/systemd/system
        mode: 0644
        remote_src: yes
        src: /usr/share/systemd/tmp.mount
        validate: /usr/bin/systemd-analyze verify %s
      when: ansible_os_family == "Debian"

    - name: Ensure nodev, noexec, and nosuid are set in the /tmp partition
      block:
        - name: Create directory for local options override for /tmp partition
          file:
            mode: 0755
            path: /etc/systemd/system/tmp.mount.d
            state: directory
        - name: Create local options override for the /tmp partition
          copy:
            content: |
              [Mount]
              Options=mode=1777,strictatime,nosuid,nodev,noexec
            dest: /etc/systemd/system/tmp.mount.d/options.conf
            mode: 0644

    # Note that we intentionally do not start the tmp.mount service
    # now.  This allows Ansible to continue using /tmp for executable
    # files while we finish building the AMI; otherwise, the final
    # step where we remove the "admin" user from the AMI fails due to
    # /tmp being noexec.
    - name: Enable and unmask tmp.mount
      systemd:
        daemon_reload: yes
        enabled: yes
        masked: no
        name: tmp.mount
  tags:
    - systemd
    - tmp

- name: Harden /dev/shm
  become: yes
  block:
    - name: Create /dev/shm entry in /etc/fstab with noexec option
      mount:
        fstype: tmpfs
        opts: rw,nodev,nosuid,noexec
        path: /dev/shm
        src: tmpfs
        state: mounted
  tags:
    - fstab
    - dev_shm
