---
- name: set login.defs configuration items
  become: "yes"
  lineinfile:
    path: /etc/login.defs
    regexp: "(?i)[^\\s #]*{{ item.name }}"
    line: "{{ item.name }} {{ item.value }}"
    state: present
  tags:
    - login.defs
  loop:
    - { name: "PASS_MAX_DAYS", value: "365"}
    - { name: "PASS_MIN_DAYS", value: "7"}
    - { name: "PASS_WARN_AGE", value: "7"}
...
