---
- name: set permissions on /etc/ssh/sshd_config
  become: 'yes'
  file:
    path: /etc/ssh/sshd_config
    mode: 0600
    owner: root
    group: root
    state: touch
  tags:
    - sshd_config
    - sshd

- name: set ssh configuration items
  become: 'yes'
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "(?i)[^\\s #]*{{ item.name }}"
    line: "{{ item.name }} {{ item.value }}"
    state: present
  tags:
    - sshd_config
    - sshd
  loop:
    - { name: "AllowTcpForwarding", value: "no"}
    - { name: "ClientAliveCountMax", value: "0"}
    - { name: "ClientAliveInterval", value: "300"}
    - { name: "HostbasedAuthentication", value: "no"}
    - { name: "IgnoreRhosts", value: "yes"}
    - { name: "LogLevel", value: "{{ sshd_log_level }}"}
    - { name: "LoginGraceTime", value: "20"}
    - { name: "MaxAuthTries", value: "{{ sshd_max_auth_tries }}"}
    - { name: "MaxSessions", value: "4"}
    - { name: "MaxStartups", value: "10:30:60"}
    - { name: "PermitEmptyPasswords", value: "no"}
    - { name: "PermitRootLogin", value: "no"}
    - { name: "PermitUserEnvironment", value: "no"}
    - { name: "Protocol", value: "2"}
    - { name: "UsePAM", value: "yes"}
    - { name: "X11Forwarding", value: "no"}
  notify:
    - restart sshd

# Only the RedHat instances fail the related compliance check
- name: Set ssh ciphers, MAC algorithms, and kex algorithms (RedHat)
  become: yes
  lineinfile:
    line: "{{ item.name }} {{ item.value }}"
    path: /etc/crypto-policies/back-ends/opensshserver.config
    regexp: "^{{ item.name }}"
  loop:
    - {
    name: Ciphers,
    value: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
    }
    - {
    name: KexAlgorithms,
    value: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
    }
    - {
    name: MACs,
    value: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
    }
  notify:
    - restart sshd
  tags:
    - sshd_config
    - sshd
  when:
    - ansible_os_family == "RedHat"
...
