---
# The hardening Nessus compliance scan uses nmcli to test
- name: Install network-manager on Debian
  become: yes
  package:
    name:
      - network-manager
  when:
    - ansible_os_family == "Debian"

- name: disable misc kernel modules
  become: 'yes'
  lineinfile:
    dest: /etc/modprobe.d/disablemod.conf
    line: "install {{ item }} /bin/true"
    mode: 0644
    owner: root
    group: root
    state: present
    create: 'yes'
  with_items:
    - "{{ misc_modules_blocklist }}"
  tags:
    - modprobe
...
