---
# The hardening Nessus compliance scan uses nmcli to test on Debian
- name: Network-manager tasks on Debian
  block:
    - name: Install network-manager on Debian
      become: yes
      package:
        name:
          - network-manager
    - name: Turn off wireless interfaces on Debian
      become: yes
      command: nmcli radio all off
  when:
    - ansible_os_family == "Debian"

- name: disable misc kernel modules
  become: 'yes'
  lineinfile:
    dest: /etc/modprobe.d/disablemod.conf
    line: "install {{ item }} /bin/true"
    mode: 0644
    owner: root
    group: root
    state: present
    create: 'yes'
  with_items:
    - "{{ misc_modules_blocklist }}"
  tags:
    - modprobe
...
