---
- name: sudo use_pty
  become: 'yes'
  lineinfile:
    line: "Defaults use_pty"
    dest: /etc/sudoers.d/011_use_pty
    mode: 0440
    state: present
    create: 'yes'
  tags:
    - sudo

- name: sudo configure logfile
  become: 'yes'
  lineinfile:
    line: 'Defaults logfile="/var/log/sudo.log"'
    dest: /etc/sudoers.d/012_logfile
    mode: 0440
    state: present
    create: 'yes'
  tags:
    - sudo
