---
- name: Set permissions on grub files
  become: yes
  block:
    - name: Set permissions on /boot/grub/grub.cfg
      block:
        - name: Check if /boot/grub/grub.cfg exists
          stat:
            path: /boot/grub/grub.cfg
          register: grub_cfg
        - name: Set permissions on /boot/grub/grub.cfg
          file:
            group: root
            mode: 0600
            owner: root
            path: /boot/grub/grub.cfg
          when: grub_cfg.stat.exists
    - name: Set permissions on /boot/grub/grub.conf
      block:
        - name: Check if /boot/grub/grub.conf exists
          stat:
            path: /boot/grub/grub.conf
          register: grub_conf
        - name: Set permissions on /boot/grub/grub.conf
          file:
            group: root
            mode: 0600
            owner: root
            path: /boot/grub/grub.conf
          when: grub_conf.stat.exists
    - name: Set permissions on /boot/grub/menu.lst
      block:
        - name: Check if /boot/grub/menu.lst exists
          stat:
            path: /boot/grub/menu.lst
          register: menu_lst
        - name: Set permissions on /boot/grub/menu.lst
          file:
            group: root
            mode: 0600
            owner: root
            path: /boot/grub/menu.lst
          when: menu_lst.stat.exists
    - name: Set permissions on /boot/grub2/grub.cfg
      block:
        - name: Check if /boot/grub2/grub.cfg exists
          stat:
            path: /boot/grub2/grub.cfg
          register: grub2_cfg
        - name: Set permissions on /boot/grub2/grub.cfg
          file:
            group: root
            mode: 0600
            owner: root
            path: /boot/grub2/grub.cfg
          when: grub2_cfg.stat.exists
  tags:
    - grub

- name: Ensure AppArmor is enabled in the bootloader configuration (Debian)
  lineinfile:
    regexp: '^GRUB_CMDLINE_LINUX="(.*)(?<!apparmor=1 security=apparmor)"'
    line: 'GRUB_CMDLINE_LINUX="\1 apparmor=1 security=apparmor"'
    dest: /etc/default/grub
    backrefs: yes
    state: present
  register: grub_updated
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - apparmor
    - grub

- name: Update grub
  command: update-grub
  become: yes
  when: grub_updated["changed"]
